config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users, only: %i[index]
  resources :foods, only: %i[index new create destroy]

  resources :recipes, only: %i[index new show create destroy] do
    resources :recipe_foods, only: %i[new create show destroy]
  end
  resources :recipe_foods, only: %i[new new create destroy]
  resources :public_recipes, only: %i[index]
  resources :general_shopping_lists, only: %i[index]

  root to: 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes, through: :recipe_foods
  has_many :recipe_foods, dependent: :delete_all

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :delete_all
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def list_all_public_recipes
    public_recipes.order('created_at ASC')
  end

  def total_food_items
    foods.size
  end

  def total_price
    foods.sum('price')
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = User.includes(:foods).find(current_user.id)
    @foods = @user.foods
  end

  def new
    @user = User.includes(:foods).find(current_user.id)
    @food = @user.foods.new
    render :new, locals: { food: @food }
  end

  def create
    add_food = current_user.foods.new(food_params)
    if add_food.save
      redirect_to '/foods', notice: 'Food was successfully added.'
    else
      render :new, alert: 'Failed to add food'
    end
  end

  def destroy
    @food = set_food
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Foods was deleted successfully.' }
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  before_action :authenticate_user!
  include GeneralShoppingListsHelper

  def index
    @recipes = current_user.recipes
    @foods = foods_join
    @total_price = 0
    @recipes.each do |recipe|
      @total_price += recipe.total_price
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where('public = true').order(id: :desc).includes(:foods).includes(:user)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def show; end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe.id), notice: 'Ingredient was successfully added.'
    else
      render :new, alert: 'Failed to add Recipefood'
    end
  end

  def new
    @foods = current_user.foods
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.destroy
      redirect_to recipe_path(params[:recipe_id]), notice: 'Successfully deleted!'
    else
      redirect_to recipe_path(params[:recipe_id]), alert: 'Error occured!'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_foods).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipes = set_recipe
    @foods = current_user.foods
    @recipe_foods = @recipes.recipe_foods
  end

  def new; end

  def create
    add_recipe = current_user.recipes.new(recipe_params)
    if add_recipe.save
      redirect_to '/recipes', notice: 'Recipe was successfully added.'
    else
      render :new, alert: 'Failed to add recipe'
    end
  end

  def destroy
    @recipe = set_recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipes was deleted successfully.' }
    end
  end

  private

  def set_recipe
    @recipe = current_user.recipes.includes(:recipe_foods).find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_lists_helper.rb
module GeneralShoppingListsHelper
  def foods_join
    Food.joins(:recipe_foods).where(user_id: current_user.id)
  end
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<div class="center">
  <div class="food-title">
    <h1>My Food List</h1>
  </div>
  <div class="button">
    <button class="add">
      <%= link_to 'Add Food', new_food_path, data: { turbo: false }, html: { method: :put} %>
    </button>
  </div>
  <table class="table table-striped table-bordered border">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name%></td>
          <td><%= food.measurement_unit%></td>
          <td><%= number_to_currency(food.price, precision:0)%></td>
          <td><%=button_to 'Delete', {:controller => :foods, :action => 'destroy', :id => food.id}, :method => :delete ,class:'danger'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
  <div class="food-title">
    <h1>Add to my list...</h1>
  </div>
  <%= form_with model: @foods, url:foods_path, scope: :food, method: :post, data: { turbo: false }, class: "form" do |form| %>
    <div class="">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder:'Food name', class: "form-control" %>
    </div>
    <div class="">
      <%= form.label :measurement_unit %>
      <%= form.text_field :measurement_unit, placeholder:'Measurements in grams or units', class: "form-control" %>
    </div>
    <div class="">
      <%= form.label :price %>
      <%= form.text_field :price, placeholder:'Price in dollars', class: "form-control" %>
    </div>
    <div class="">
      <%= form.submit "submit", class: "btn" %>
    </div>
  <% end %>

app/views/general_shopping_lists/index.html.erb
<section class="center" >
  <h1>Shopping List</h1>
  <div >
    <p>Amount of food items to buy: <%= @foods.count %> </p>
    <p> Total value of food needed: $ <%= @total_price %> </p>
  </div>

  <table >
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <% quantity=RecipeFood.joins(:food).where(food_id: food.id).sum( 'quantity') %>
        <td><%= food.name%></td>
        <td><%= quantity %></td>
        <td>$ <%= food.price * quantity %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'partials/nav' %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class='nav'>
<% if user_signed_in? %>
<%= link_to 'My Food', foods_path %> 
  <%= link_to 'My Recipes', recipes_path %>
  <%= link_to 'Our Recepies', public_recipes_path %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:'danger'%>

  <% else %>
  <%= link_to 'Sign In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path%>
<% end %>
</nav>

app/views/public_recipes/index.html.erb
<div class="center">
  <h1>Public Recipes</h1>
  <div class='public'>
  <% @public_recipes.each do |recipe| %>
    <%= link_to recipe_path(recipe) do %> 
      <div class="recipe-public-card d-flex">
        <div class="recipe-public-header">
          <h2><%= recipe.name%></h2>
          <h4>By: <%= recipe.user.name %></h4>
        </div>
        <div class="recipe-public-counter">
          <p>Total food items: <%=recipe.total_food_items%></p>
          <p>Total price: $<%=recipe.total_price%></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/recipe_foods/create.html.erb
<div class="">
  <div class="">
    <h1>Add to my Shopping List...</h1>
  </div>

  <%= form_with model: @general_shopping_lists, url:general_shopping_lists_path, scope: :general_shopping_list, method: :post, data: { turbo: false }, class: "food-form" do |form| %>
    <div class="">
      <%= form.label :name %>
      <%= form.text_field :text, class: "form-control", required: true %>
    </div>
    <div class="">
      <%= form.label :quantity %>
      <%= form.text_field :text, class: "form-control", required: true %>
    </div>
    <div class="">
      <%= form.label :price %>
      <%= form.text_field :text, class: "form-control", required: true %>
    </div>
    <div class="submit mt-3">
      <%= form.submit "submit" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/destroy.html.erb
<h1>RecipeFoods#destroy</h1>

app/views/recipe_foods/new.html.erb
<div class="">
    <h1>Add to my Shopping List...</h1>
  </div>

  <%= form_with url: recipe_recipe_foods_path(params[:recipe_id]), data: { turbo: false }, scope: :recipe_foods, class: "form" do |form| %>
    <section class="">
      <%= form.label "List of Ingredients", class: "unit-label" %>
      <%= form.select :food_id, @foods.collect { |food| [food.name, food.id] }, class: "full-width", placeholder: "Select ingredient", required: true %>
    </section>
    <div class="">
      <%= form.label :quantity %>
      <%= form.text_field :quantity, class: "form-control", required: true %>
    </div>
    <div class="">
      <%= form.submit "submit", class: "" %>
    </div>
  <% end %>

app/views/recipes/index.html.erb
<div class="center recipe">
<div>
  <h1>My list of Recipes</h1>
</div>
<div class="button">
<button class="add">
  <%= link_to 'Add a new recipe', new_recipe_path %>
</button>
</div>
<% @recipes.each do |recipe| %>
  <div class="">
    <div class="card">
      <div>
        <h1><%= link_to recipe.name, recipe_path(recipe) %></h1>
      </div>
        <p><%= recipe.description %></p>
      <div>
        <%= button_to 'Delete', recipe_path(recipe.id), method: :delete, class:'danger' %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/recipes/new.html.erb
<div class="new center">
<div >
    <h1>My New Recipe</h1>
  </div>
  <%= form_with model: @recipes, url:recipes_path, scope: :recipe, method: :post, data: { turbo: false }, class: "form" do |form| %>
    <div class="t">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: 'Name of the dish',  class: "form-control" %>
    </div>
    <div class="t">
      <%= form.label :preparation_time %>
      <%= form.text_field :preparation_time, placeholder: 'How long will it take to prep', class: "form-control" %>
    </div>
    <div class="t">
      <%= form.label :cooking_time %>
      <%= form.text_field :cooking_time, placeholder: 'How long will it take to cook', class: "form-control" %>
    </div>
    <div class="t">
      <%= form.label :how_to.. %>
      <%= form.text_area :description, placeholder: 'preparation and cooking steps', class: "form-control" %>
    </div>
    <div class="p">
      <%= form.check_box :public, class: "form-check-input", type: "checkbox", id: "flexSwitchCheckDefault" %>
      <%= form.label "Public", class: "form-check-label", for: "flexSwitchCheckDefault" %>
    </div>
    <div class="t">
      <%= form.submit "submit", class: "add" %>
    </div>
  <% end %>
  </div>

app/views/recipes/show.html.erb
<section class="center">
  <h2><%= @recipe.name %></h2>

  <div class="main">
    <div class="recipe">
      <p>Preparation time: <%=@recipe.preparation_time%> hour</p>
      <p>Cooking time: <%=@recipe.cooking_time%> hours</p>
      <p>Step go here ...</p>
    </div>
    <div>
      <% if @recipe.public %>
        <p>Public: ON</p>
      <% else %>
        <p>Public: OFF</p>
      <% end %>
    </div>
  </div>
  <div class="detail-btns d-flex">
    <button class='add'>
     <%= link_to 'Generate shopping list', general_shopping_lists_path(@recipe), data: { turbo: false }, html: { method: :put} %>
    </button>
    <button  class='add'>
      <%= link_to 'Add ingredients', new_recipe_recipe_food_url(@recipe), data: { turbo: false }, html: { method: :put} %>
    </button>
  </div>
  <div class="line-detail"></div>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name%></td>
          <td><%= recipe_food.quantity%></td>
          <td> $ <%= recipe_food.food.price %></td>
          <th scope="col">
            <%= button_to 'Remove', recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :delete, class:'danger' %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>


  <div class="recipe-btn">
    <button class="add ">
      <%= link_to "back", public_recipes_path %>
      <% link_to "back", recipes_path %>
    </button>
  </div>
</section>

app/views/users/index.html.erb
<div>
<h1>Welcome to the Recipe Page!</h1>
    </div>